/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeguridadRouteImport } from './routes/seguridad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicioServiceRouteImport } from './routes/servicio.$service'
import { Route as ReservarIdRouteImport } from './routes/reservar.$id'
import { Route as PrestadorIdRouteImport } from './routes/prestador.$id'
import { Route as AuthenticatedVerificarIdentidadRouteImport } from './routes/_authenticated.verificar-identidad'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated.reservas'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated.panel'
import { Route as AuthenticatedOnboardingPrestadorRouteImport } from './routes/_authenticated.onboarding-prestador'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated.notificaciones'
import { Route as AuthenticatedNotifConfigRouteImport } from './routes/_authenticated.notif-config'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated.favoritos'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated.cuenta'
import { Route as AuthenticatedChatReservaIdRouteImport } from './routes/_authenticated.chat.$reservaId'
import { Route as AuthenticatedAdminVerificacionesRouteImport } from './routes/_authenticated.admin.verificaciones'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated.admin.reportes'

const SeguridadRoute = SeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicioServiceRoute = ServicioServiceRouteImport.update({
  id: '/servicio/$service',
  path: '/servicio/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarIdRoute = ReservarIdRouteImport.update({
  id: '/reservar/$id',
  path: '/reservar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadorIdRoute = PrestadorIdRouteImport.update({
  id: '/prestador/$id',
  path: '/prestador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerificarIdentidadRoute =
  AuthenticatedVerificarIdentidadRouteImport.update({
    id: '/verificar-identidad',
    path: '/verificar-identidad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingPrestadorRoute =
  AuthenticatedOnboardingPrestadorRouteImport.update({
    id: '/onboarding-prestador',
    path: '/onboarding-prestador',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotifConfigRoute =
  AuthenticatedNotifConfigRouteImport.update({
    id: '/notif-config',
    path: '/notif-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatReservaIdRoute =
  AuthenticatedChatReservaIdRouteImport.update({
    id: '/chat/$reservaId',
    path: '/chat/$reservaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVerificacionesRoute =
  AuthenticatedAdminVerificacionesRouteImport.update({
    id: '/admin/verificaciones',
    path: '/admin/verificaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/admin/reportes',
    path: '/admin/reportes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguridad': typeof SeguridadRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notif-config': typeof AuthenticatedNotifConfigRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/onboarding-prestador': typeof AuthenticatedOnboardingPrestadorRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/verificar-identidad': typeof AuthenticatedVerificarIdentidadRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/reservar/$id': typeof ReservarIdRoute
  '/servicio/$service': typeof ServicioServiceRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/chat/$reservaId': typeof AuthenticatedChatReservaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguridad': typeof SeguridadRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notif-config': typeof AuthenticatedNotifConfigRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/onboarding-prestador': typeof AuthenticatedOnboardingPrestadorRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/verificar-identidad': typeof AuthenticatedVerificarIdentidadRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/reservar/$id': typeof ReservarIdRoute
  '/servicio/$service': typeof ServicioServiceRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/chat/$reservaId': typeof AuthenticatedChatReservaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguridad': typeof SeguridadRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/notif-config': typeof AuthenticatedNotifConfigRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/onboarding-prestador': typeof AuthenticatedOnboardingPrestadorRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/verificar-identidad': typeof AuthenticatedVerificarIdentidadRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/reservar/$id': typeof ReservarIdRoute
  '/servicio/$service': typeof ServicioServiceRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/_authenticated/chat/$reservaId': typeof AuthenticatedChatReservaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/seguridad'
    | '/cuenta'
    | '/favoritos'
    | '/notif-config'
    | '/notificaciones'
    | '/onboarding-prestador'
    | '/panel'
    | '/reservas'
    | '/verificar-identidad'
    | '/prestador/$id'
    | '/reservar/$id'
    | '/servicio/$service'
    | '/admin/reportes'
    | '/admin/verificaciones'
    | '/chat/$reservaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/seguridad'
    | '/cuenta'
    | '/favoritos'
    | '/notif-config'
    | '/notificaciones'
    | '/onboarding-prestador'
    | '/panel'
    | '/reservas'
    | '/verificar-identidad'
    | '/prestador/$id'
    | '/reservar/$id'
    | '/servicio/$service'
    | '/admin/reportes'
    | '/admin/verificaciones'
    | '/chat/$reservaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/buscar'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/seguridad'
    | '/_authenticated/cuenta'
    | '/_authenticated/favoritos'
    | '/_authenticated/notif-config'
    | '/_authenticated/notificaciones'
    | '/_authenticated/onboarding-prestador'
    | '/_authenticated/panel'
    | '/_authenticated/reservas'
    | '/_authenticated/verificar-identidad'
    | '/prestador/$id'
    | '/reservar/$id'
    | '/servicio/$service'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/verificaciones'
    | '/_authenticated/chat/$reservaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SeguridadRoute: typeof SeguridadRoute
  PrestadorIdRoute: typeof PrestadorIdRoute
  ReservarIdRoute: typeof ReservarIdRoute
  ServicioServiceRoute: typeof ServicioServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicio/$service': {
      id: '/servicio/$service'
      path: '/servicio/$service'
      fullPath: '/servicio/$service'
      preLoaderRoute: typeof ServicioServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/$id': {
      id: '/reservar/$id'
      path: '/reservar/$id'
      fullPath: '/reservar/$id'
      preLoaderRoute: typeof ReservarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestador/$id': {
      id: '/prestador/$id'
      path: '/prestador/$id'
      fullPath: '/prestador/$id'
      preLoaderRoute: typeof PrestadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verificar-identidad': {
      id: '/_authenticated/verificar-identidad'
      path: '/verificar-identidad'
      fullPath: '/verificar-identidad'
      preLoaderRoute: typeof AuthenticatedVerificarIdentidadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding-prestador': {
      id: '/_authenticated/onboarding-prestador'
      path: '/onboarding-prestador'
      fullPath: '/onboarding-prestador'
      preLoaderRoute: typeof AuthenticatedOnboardingPrestadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notif-config': {
      id: '/_authenticated/notif-config'
      path: '/notif-config'
      fullPath: '/notif-config'
      preLoaderRoute: typeof AuthenticatedNotifConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$reservaId': {
      id: '/_authenticated/chat/$reservaId'
      path: '/chat/$reservaId'
      fullPath: '/chat/$reservaId'
      preLoaderRoute: typeof AuthenticatedChatReservaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/verificaciones': {
      id: '/_authenticated/admin/verificaciones'
      path: '/admin/verificaciones'
      fullPath: '/admin/verificaciones'
      preLoaderRoute: typeof AuthenticatedAdminVerificacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedNotifConfigRoute: typeof AuthenticatedNotifConfigRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedOnboardingPrestadorRoute: typeof AuthenticatedOnboardingPrestadorRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedVerificarIdentidadRoute: typeof AuthenticatedVerificarIdentidadRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminVerificacionesRoute: typeof AuthenticatedAdminVerificacionesRoute
  AuthenticatedChatReservaIdRoute: typeof AuthenticatedChatReservaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedNotifConfigRoute: AuthenticatedNotifConfigRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedOnboardingPrestadorRoute: AuthenticatedOnboardingPrestadorRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedVerificarIdentidadRoute: AuthenticatedVerificarIdentidadRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminVerificacionesRoute: AuthenticatedAdminVerificacionesRoute,
  AuthenticatedChatReservaIdRoute: AuthenticatedChatReservaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BuscarRoute: BuscarRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SeguridadRoute: SeguridadRoute,
  PrestadorIdRoute: PrestadorIdRoute,
  ReservarIdRoute: ReservarIdRoute,
  ServicioServiceRoute: ServicioServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
